#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup. #
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
# global settings

yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse off
yabai -m config window_origin_display default
yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_opacity off
yabai -m config window_opacity_duration 0.0
yabai -m config window_shadow float
yabai -m config window_border on
yabai -m config window_border_width 4

yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.90
yabai -m config split_ratio 0.50
yabai -m config auto_balance off
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

# general space settings
yabai -m config layout bsp
yabai -m config external_bar all:38:0
yabai -m config top_padding 0
yabai -m config bottom_padding 4
yabai -m config left_padding 4
yabai -m config right_padding 4
yabai -m config window_gap 4

# Disable specific apps
yabai -m rule --add label="iDingTalk" app="^iDingTalk$" manage=off
yabai -m rule --add label="访达" app="^访达$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" manage=off
yabai -m rule --add label="Preview" app="^Preview$" manage=off
yabai -m rule --add label="设置" app="^系统设置$" title=".*" manage=off
yabai -m rule --add label="Settings" app="^Settings$" title=".*" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="System Information" app="System Information" title="System Information" manage=off
yabai -m rule --add label="Racast" app="Raycast" manage=off
yabai -m rule --add label="WeChat" app="^WeChat$" manage=off
yabai -m rule --add label="Pixcall" app="^Pixcall$" manage=off
yabai -m rule --add label="Eagle" app="^Eagle$" manage=off
yabai -m rule --add label="Elmedia Player" app="^Elmedia Player$" manage=off
yabai -m rule --add label="CleanMyMac" app="^CleanMyMac$" manage=off
yabai -m rule --add label="BetterZip" app="^BetterZip$" manage=off
yabai -m rule --add label="ImageOptim" app="^ImageOptim$" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off

# space label
yabai -m space 1 --label main
yabai -m space 2 --label web
yabai -m space 3 --label apps
yabai -m space 4 --label misc
yabai -m space 5 --label gtd
yabai -m space 6 --label safari
yabai -m space 7 --label chrome

yabai -m rule --add app="^Ghostty$" space=main
yabai -m rule --add app="^Arc$" space=web
yabai -m rule --add app="^Safari$" space=safari
yabai -m rule --add app="^Google Chrome$" space=chrome
yabai -m rule --add app="^Pixcall$" space=misc
yabai -m rule --add app="^Eagle$" space=misc

echo "yabai configuration loaded.."
